name: phylo-analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - snakemake-minimal =7.0.1
  - samtools >=1.3
  - clustalo >=1.2.4
  - phyml =3.3.20200621
  - r-base =4.0.2
  - biopython=1.79
  - r-ape=5.6
  - r-stringr=1.4.0

